# Generated by Django 4.2.23 on 2025-07-02 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPIDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('contactno', models.CharField(blank=True, max_length=100, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_projectpi_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irisid', models.CharField(blank=True, max_length=200, null=True)),
                ('projectid', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('filenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('proposalfile', models.FileField(upload_to='pdfs/')),
                ('prcrecommend', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('prccomment', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('projectpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectpi_project_detail', to='account.projectpidetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_project_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('First_Year', 'First Year'), ('Second_year', 'Second Year'), ('Third_year', 'Third Year'), ('Fourth_year', 'Fourth Year')], max_length=200, null=True)),
                ('salary', models.FloatField()),
                ('contingencies', models.FloatField()),
                ('non_contingencies', models.FloatField()),
                ('recurring', models.FloatField()),
                ('travel', models.FloatField()),
                ('overhead_expens', models.FloatField()),
                ('total', models.IntegerField()),
                ('fileupload', models.FileField(upload_to='pdfs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('projectdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdetail_financial_detail', to='account.projectdetail')),
                ('projectpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectpi_financial_detail', to='account.projectpidetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_financial_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
    ]
