# Generated by Django 4.2.23 on 2025-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
