# Generated by Django 4.2.23 on 2025-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_district_dummy_state_dummy_state_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdetail',
            name='total',
            field=models.FloatField(),
        ),
    ]
