# Generated by Django 4.2.23 on 2025-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_financialdetail_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpidetail',
            name='duration',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
