# Generated by Django 4.2.23 on 2025-07-07 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_remove_projectpidetail_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='irisid',
        ),
        migrations.AddField(
            model_name='projectpidetail',
            name='area_expertise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpidetail',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpidetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpidetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpidetail',
            name='qualification',
            field=models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MSC', 'MSC'), ('Phd', 'Phd'), ('M.Tech', 'M.Tech')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InstituteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sortcode', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_type', models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=100, null=True)),
                ('contactno', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_institute_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='projectpidetail',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_projectpi_detail', to='account.institutedetail'),
        ),
    ]
