# Generated by Django 4.2.23 on 2025-07-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_projectdetail_irisid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpidetail',
            old_name='district',
            new_name='district_pi',
        ),
        migrations.RenameField(
            model_name='projectpidetail',
            old_name='state',
            new_name='state_pi',
        ),
    ]
