# Generated by Django 4.2.23 on 2025-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_district_projectpidetail_district_pi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdetail',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
