# Generated by Django 4.2.23 on 2025-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_financialdetail_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='approvalfile',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='eofficnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
