# Generated by Django 4.2.23 on 2025-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_projectdetail_approvalfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='projectpi',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='projectpi',
            field=models.ManyToManyField(to='account.projectpidetail'),
        ),
    ]
