# Generated by Django 4.2.23 on 2025-07-23 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_remove_projectdetail_projectpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.FloatField()),
                ('contingencies', models.FloatField()),
                ('non_contingencies', models.FloatField()),
                ('recurring', models.FloatField()),
                ('travel', models.FloatField()),
                ('overhead_expens', models.FloatField()),
                ('total', models.FloatField()),
                ('fileupload', models.FileField(upload_to='pdfs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_ub_detail', to='account.financialdetail')),
                ('projectdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdetail_ub_detail', to='account.projectdetail')),
                ('projectpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectpi_ub_detail', to='account.projectpidetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ub_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseBuget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.FloatField()),
                ('contingencies', models.FloatField()),
                ('non_contingencies', models.FloatField()),
                ('recurring', models.FloatField()),
                ('travel', models.FloatField()),
                ('overhead_expens', models.FloatField()),
                ('total', models.FloatField()),
                ('fileupload', models.FileField(upload_to='pdfs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_release_detail', to='account.financialdetail')),
                ('projectdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdetail_release_detail', to='account.projectdetail')),
                ('projectpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectpi_release_detail', to='account.projectpidetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_release_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
