# Generated by Django 4.2.23 on 2025-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_usedbalance_releasebuget'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasebuget',
            name='release_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedbalance',
            name='uc_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
