# Generated by Django 4.2.23 on 2025-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_releasebuget_release_no_usedbalance_uc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdetail',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='interest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='remainamount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='releasebuget',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usedbalance',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usedbalance',
            name='interest',
            field=models.FloatField(default=0.0),
        ),
    ]
