# Generated by Django 4.2.23 on 2025-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_financialdetail_comment_financialdetail_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdetail',
            name='contingencies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialdetail',
            name='non_contingencies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialdetail',
            name='overhead_expens',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialdetail',
            name='recurring',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialdetail',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialdetail',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialdetail',
            name='travel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='contingencies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='non_contingencies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='overhead_expens',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='recurring',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='travel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='contingencies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='non_contingencies',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='overhead_expens',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='recurring',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='travel',
            field=models.FloatField(default=0.0),
        ),
    ]
