# Generated by Django 4.2.23 on 2025-07-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_financialdetail_contingencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='projectpi',
            field=models.ManyToManyField(related_name='project_projectpi', to='account.projectpidetail'),
        ),
    ]
