# Generated by Django 4.2.23 on 2025-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_projectdetail_projectpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='prc_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
