# Generated by Django 4.2.23 on 2025-08-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_projectdetail_prc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdetail',
            name='fileupload',
        ),
    ]
