# Generated by Django 4.2.23 on 2025-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_financialdetail_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='proposalfile',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='releasebuget',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='usedbalance',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
