# Generated by Django 4.2.23 on 2025-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_projectdetail_proposalfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasebuget',
            name='release_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='releasebuget',
            unique_together={('projectpi', 'projectdetail', 'finance', 'release_no')},
        ),
    ]
