# Generated by Django 4.2.23 on 2025-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_releasebuget_release_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdetail',
            name='carry_forward_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='interest_tr_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='remain_tr_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='transfer_from_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financialdetail',
            name='uc_submit',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=100),
        ),
    ]
